### ISSUE TITLE
[BUG] Hive Metastore does not start.

### ISSUE THREAD

**Issue by lkellermann** [lkellermann/sparkify-airflow#1]
**Describe the bug**
Hive metastorre docker container keeps restarting.

Found this in the logs:
 ```
[1/100] namenode:9870 is available.
[1/100] datanode:9864 is available.
[1/100] postgres:5432 is available.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/hive/lib/log4j-slf4j-impl-2.10.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357)
        at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338)
        at org.apache.hadoop.mapred.JobConf.setJar(JobConf.java:536)
        at org.apache.hadoop.mapred.JobConf.setJarByClass(JobConf.java:554)
        at org.apache.hadoop.mapred.JobConf.<init>(JobConf.java:448)
        at org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:5141)
        at org.apache.hadoop.hive.conf.HiveConf.<init>(HiveConf.java:5104)
        at org.apache.hive.beeline.HiveSchemaTool.<init>(HiveSchemaTool.java:96)
        at org.apache.hive.beeline.HiveSchemaTool.main(HiveSchemaTool.java:1473)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
2021-12-05 13:20:52: Starting Hive Metastore Server
```

**To Reproduce**
1. Execute ./start.sh.
2. Execute ```docker container ls``` and look at `sparkify-airflow_hive-metastore` status. Wait a little and repeat.
3. You'll see that this container keeps restarting and the containers that depends on `hive-metastore` does not start up.

**Expected behavior**
`hive-metastore` should start as also those containers that depends on it.

**Comment by lkellermann** [comment]
I found [this](https://stackoverflow.com/questions/58176627/how-can-i-ask-hive-to-provide-more-detailed-error). Checking the Guava files, I found the following:
- On Hive Server: ```/opt/hive/lib/guava-19.0.jar```
- On Namenode: ```/opt/hadoop/share/hadoop/common/lib/guava-27.0-jre.jar ```

In the same thread in SO above, `Tim Yates` provided a good solution. 

Now there is other issue:

```
Caused by: org.postgresql.util.PSQLException: The authentication type 10 is not supported. Check that you have configured the pg_hba.conf file to include the client's IP address or subnet, and that it is using an authentication scheme supported by the driver.
```

**Comment by lkellermann** [comment]
Found out that PostgreSQL 14 is too new. Downgrading to PostgreSQL image to 12 and upgrading the driver to `postgresql-42.3.1.jar` seems to solve the issue.
```
 docker container ls
CONTAINER ID   IMAGE                             COMMAND                  CREATED         STATUS                   PORTS                                                                                                                 NAMES
7bc1544486fa   sparkify-airflow_hive-webhcat     "./entrypoint.sh ./s…"   8 minutes ago   Up 7 minutes (healthy)   10000-10002/tcp, 50111/tcp                                                                                            hive-webhcat
54e015673046   sparkify-airflow_hue              "./entrypoint.sh ./s…"   8 minutes ago   Up 7 minutes (healthy)   0.0.0.0:32762->8888/tcp, :::32762->8888/tcp                                                                           hue
e54a66b57482   sparkify-airflow_hive-server      "./entrypoint.sh ./s…"   8 minutes ago   Up 8 minutes (healthy)   10001/tcp, 0.0.0.0:32760->10000/tcp, :::32760->10000/tcp, 0.0.0.0:32759->10002/tcp, :::32759->10002/tcp               hive-server
17971b2b0582   sparkify-airflow_livy             "./entrypoint"           8 minutes ago   Up 8 minutes (healthy)   0.0.0.0:32758->8998/tcp, :::32758->8998/tcp                                                                           livy
4d3e10070e0e   sparkify-airflow_hive-metastore   "./entrypoint.sh ./s…"   8 minutes ago   Up 8 minutes (healthy)   10000-10002/tcp, 0.0.0.0:32761->9083/tcp, :::32761->9083/tcp                                                          hive-metastore
60aec8d2eb6d   sparkify-airflow_spark-worker     "./entrypoint.sh ./s…"   8 minutes ago   Up 8 minutes (healthy)   10000-10002/tcp, 0.0.0.0:32764->8081/tcp, :::32764->8081/tcp                                                          sparkify-airflow_spark-worker_1
8993a83b4cf1   sparkify-airflow_datanode         "./entrypoint.sh ./s…"   8 minutes ago   Up 8 minutes (healthy)   9864/tcp                                                                                                              datanode
93375ae86a59   sparkify-airflow_airflow          "./entrypoint.sh ./s…"   8 minutes ago   Up 8 minutes (healthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 10000-10002/tcp                                                            airflow
650b99e9bcca   wodby/adminer:latest              "/entrypoint.sh php …"   8 minutes ago   Up 8 minutes (healthy)   0.0.0.0:32767->9000/tcp, :::32767->9000/tcp                                                                           adminer
b9024eaa18e7   sparkify-airflow_postgres         "docker-entrypoint.s…"   8 minutes ago   Up 8 minutes (healthy)   0.0.0.0:32769->5432/tcp, :::32769->5432/tcp                                                                           postgres
830a5a449420   sparkify-airflow_spark-master     "./entrypoint.sh ./s…"   8 minutes ago   Up 8 minutes (healthy)   6066/tcp, 10000-10002/tcp, 0.0.0.0:32765->7077/tcp, :::32765->7077/tcp, 0.0.0.0:32766->8082/tcp, :::32766->8082/tcp   spark-master
45649807997e   sparkify-airflow_namenode         "./entrypoint.sh ./s…"   8 minutes ago   Up 8 minutes (healthy)   0.0.0.0:32763->9870/tcp, :::32763->9870/tcp                                                                           namenode
```
